export const REPOSITORY_REQUEST = "repository/REPOSITORY_REQUEST";
export const REPOSITORY_SUCCESS = "repository/REPOSITORY_SUCCESS";
export const REPOSITORY_FAILURE = "repository/REPOSITORY_FAILURE";

export default {
  REPOSITORY_REQUEST,
  REPOSITORY_SUCCESS,
  REPOSITORY_FAILURE
};
