export const REQUEST_COUNT_LIMIT_EXCEED =
  "requestLimit/REQUEST_COUNT_LIMIT_EXCEED";
export const REQUEST_COUNT_LIMIT_NOT_EXCEED =
  "requestLimit/REQUEST_COUNT_LIMIT_NOT_EXCEED";

export const REQUEST_LIMIT_REQUEST = "requestLimit/REQUEST_LIMIT_REQUEST";

export default {
  REQUEST_COUNT_LIMIT_EXCEED,
  REQUEST_COUNT_LIMIT_NOT_EXCEED,
  REQUEST_LIMIT_REQUEST
};
